name = "bach-itinerary"
main = "dist/server/bach-itinerary.js"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
  { name = "main", class_name = "BridalJeopardyServer" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BridalJeopardyServer"]

[build]
command = "npm run build:server"